# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 385964a48e2c0dad525514d807fe350902a7dc8601aa5ce7797f8743433ab43ee90465d3a5e1174bf4e854b700b8e6a5ec4235de5733a001a756b77229d714ca

test:
  secret_key_base: 871f33d065f87a690e8cc34c3924a719d41cf6a716da731afdd7a46cd9fb8b5056e9ba7688aadf2d7bd2b63acdf2c8847b532dedf8ed6433f7724308538e9217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
